dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
  - "3.6"
  - "2.7"
env:
  - DJANGO=2.2 DB=sqlite
  - DJANGO=2.2 DB=postgres
  - DJANGO=2.2 DB=mysql
  - DJANGO=3.0 DB=sqlite
  - DJANGO=3.0 DB=postgres
  - DJANGO=3.0 DB=mysql
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - cd decide
  - coverage run --branch --source=. ./manage.py test store/ --keepdb --with-xunit
  - coverage xml
  - python-codacy-coverage -r coverage.xml
branches:
  only:
    - desarrollo
