dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - cd decide
  - cp travis_local_settings.py local_settings.py
  - coverage run --branch --source=. ./manage.py test mixnet/ --keepdb 
  - coverage xml
  - python-codacy-coverage -r coverage.xml
deploy:
  provider: heroku
  app: egc-carsantir-prueba
  strategy: git
  api_key: 
    secure: nU5Hr3D47f1dKiaZN6P8SvMgV90SN4dWja5laOcqDXIYGsX8lWs0lZ95njREy7zI64AcuTcwEdS92ajq9Xke8Tq572Xk4VYHMq3XLyALJqlcC1WYIhExGSuor2UsEXMZdcGC8RYFlu5nu8xoCFTHwgtXU2MGPL9fkKHKSL8BVpIB4IHbNdswDJBXGWxxaqrzRk1PbiNMsEr8sXBgZt+AtF9bSoUsYiJWS9lEWCAI46P8q2vLDmGTbr/8kuhrB3zxizAUPW5KvHMN4MD8+DUblaGJFhYSj+jzHLg5ipRyx8ojQvpkQFdnqk4yG2dB9JdvoxYCtI9TBLBfKx2CDXT4UAwySH5tEWm34h07jKXDmzfdS7wyLNVeKcyEVD8POapqGqTUHKjk9tiz8sYfpV90DQbiX718wTzdw6iZvWSW9vOJ/8MMAFzHD88GgTPRQISzoAKxFBIw/qbbDOtTcpYBfhfWGUKvY8LzbV/sZD0CIIYOE4xFPpy6cX/TKsC8B4KSqjavSBm/sSXDg+yv+1Yxabsu9uq2TcEn1kWpGzNbPqjvqBmUsWhvodWI1Hp7pAG51hkZmhOBAsofG6bW6iYvugXS9P0ktDntUoDXEW30EeuohMUT33WiozNg5DncRgrdGoGYJTt57md5XG0htoDYSu8mIqgUKTTEjo1KttL3a2M=
